spring:
  application:
    name: GSM-JOVA-v1
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${url}
    username: ${id}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080